[project]
name = "static-opiniosn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "jinja2>=3.1.6",
    "requests>=2.32.5",
    "tqdm>=4.67.1",
]
